# 导入numpy库并简写为 np

In [1]:
import numpy as np

# 打印numpy的版本和配置说明

In [2]:
print(np.__version__)
np.show_config

1.16.4


<function numpy.__config__.show()>

# 创建一个长度为10的空向量

In [3]:
Z= np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 如何找到任何一个数组的内存大小？

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


5. 如何从命令行得到numpy中add函数的说明文档?

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6. 创建一个长度为10并且除了第五个值为1的空向量

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. 创建一个值域范围从10到49的向量

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. 反转一个向量(第一个元素变为最后一个) 

In [8]:
Z = np.arange(5)
Z = Z[::-1]
print(Z)

[4 3 2 1 0]


9. 创建一个 3x3 并且值从0到8的矩阵

In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


11. 创建一个 3x3 的单位矩阵

In [11]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. 创建一个 3x3x3的随机数组 

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.71504555 0.50737896 0.99035689]
  [0.4822851  0.95120698 0.06855759]
  [0.90741852 0.5443868  0.3272028 ]]

 [[0.87655872 0.99046945 0.3001295 ]
  [0.37978815 0.22072359 0.51976272]
  [0.16281751 0.52042975 0.56056824]]

 [[0.29645223 0.33343899 0.07326643]
  [0.26089844 0.94213447 0.1590688 ]
  [0.24175971 0.89007862 0.54720237]]]


13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin,Zmax)

0.0028281383653729897 0.990651524053856


14. 创建一个长度为30的随机向量并找到它的平均值

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5197473915903152


15. 创建一个二维数组，其中边界值为1，其余值为0 

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. 对于一个存在在数组，如何添加一个用0填充的边界? 

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. 以下表达式运行的结果分别是什么?

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 

In [18]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [19]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [20]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [21]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. 对一个5x5的随机矩阵做归一化

In [22]:
Z = np.random.random((5,5))
Zmax,Zmin = Z.max(),Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.21459853 0.62284078 0.63162063 1.         0.75132016]
 [0.39020672 0.9617014  0.04232164 0.62111437 0.92174741]
 [0.74833416 0.21430548 0.74553797 0.72141812 0.38950048]
 [0.32201177 0.48288984 0.10943863 0.16559055 0.13497644]
 [0.8910038  0.84856691 0.01205773 0.83682507 0.        ]]


23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [23]:
color = np.dtype([("r",np.ubyte, 1),
                 ("g", np.ubyte, 1),
                 ("b", np.ubyte, 1),
                 ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ 

In [24]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. 给定一个一维数组，对其在3到8之间的所有元素取反 

In [25]:
Z = np.arange(11)
Z[(3<Z) & (Z<=8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26. 下面脚本运行后的结果是什么?

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. 考虑一个整数向量Z,下列表达合法的是哪个? 

In [27]:
Z = np.arange(5)
Z**Z
2<<Z>>2
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28. 下列表达式的结果分别是什么?

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

29. 如何从零位对浮点数组做舍入 ?

In [ ]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

30. 如何找到两个数组中的共同元素?

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?

In [ ]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

32. 下面的表达式是正确的吗? 

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

33. 如何得到昨天，今天，明天的日期?

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

34. 如何得到所有与2016年7月对应的日期？

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

36. 用五种不同的方法去提取一个随机数组的整数部分

In [ ]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

37. 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [ ]:
def generate():
    for x in range(10):
        yield x
    Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

40. 创建一个长度为10的随机向量，并将其排序

In [ ]:
Z = np.random.random(10)
Z.sort()
print (Z)

41.对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

42. 对于两个随机数组A和B，检查它们是否相等

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

43. 创建一个只读数组(read-only)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

45. 创建一个长度为10的向量，并将向量中最大值替换为1

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 1
print (Z)

46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(Z)

47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

48. 打印每个numpy标量类型的最小值和最大值？ 

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

49. 如何打印一个数组中的所有数值?

In [ ]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

50. 给定标量时，如何找到数组中最接近标量的值？

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])